apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restrict-image-registries
  namespace: demo
  annotations:
    policies.kyverno.io/title: Restrict image registries
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod, Deployment
    policies.kyverno.io/description: >-
      Docker Hub has thousands of typosquatted images and does not run
      vulnerability scans by default. This policy flags images pulled
      from docker.io/library.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: deny-untrusted-registry-deployment
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "Images must be pulled from an approved registry, not docker.io/library."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - image: "!docker.io/library/*"

    - name: deny-untrusted-registry-pod
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Images must be pulled from an approved registry, not docker.io/library."
        pattern:
          spec:
            containers:
              - image: "!docker.io/library/*"
