global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
  extraArgs:
    - --insecure

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true

